// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTCyIfGuCe5dB3yhV1Z8yIkyHSt6mrNxM',
    appId: '1:689705725823:android:1e11573e5eec0ef1b6344a',
    messagingSenderId: '689705725823',
    projectId: 'milk-bazzar-f8f58',
    storageBucket: 'milk-bazzar-f8f58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAubQqQsDlrz01ApffkYBqs9-ndiVJD8lA',
    appId: '1:689705725823:ios:4e383199167a29fab6344a',
    messagingSenderId: '689705725823',
    projectId: 'milk-bazzar-f8f58',
    storageBucket: 'milk-bazzar-f8f58.appspot.com',
    androidClientId: '689705725823-bqip9lndff2b19o6l428rchcrtsll3qt.apps.googleusercontent.com',
    iosClientId: '689705725823-q3s41cqvueutd92it3sds7j7cg2tqu35.apps.googleusercontent.com',
    iosBundleId: 'com.example.milkBazzar',
  );
}
